all:
  vars:
    control_plane_endpoint: 10.13.37.200
    load_balancer_ip_pool:
      - 10.13.37.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.13.37.124, mac: 'BC:24:11:E8:25:07', disk: sda, network_interface: net0}
