elementweb:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.myalin.ru"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    hosts:
      - host: &frontend_host chat.myalin.ru
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: element-tls-certificate
        hosts:
          - *frontend_host
  config:
    default:
      base_url: https://matrix.myalin.ru
      server_name: myalin.ru

dendrite:
  dendrite_config:
    global:
      server_name: matrix.myalin.ru
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostName: matrix.myalin.ru
    tls:
      - hosts:
          - matrix.myalin.ru
        secretName: matrix-tls-certificate
  postgresql:
    enabled: true
